/* Auto-generated by genmsg_cpp for file /home/hcrl-nuc/workspaces/search_ws/src/a1_autonomy/amrl_msgs/msg/HumanStateArrayMsg.msg */
#ifndef AMRL_MSGS_MESSAGE_HUMANSTATEARRAYMSG_H
#define AMRL_MSGS_MESSAGE_HUMANSTATEARRAYMSG_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "amrl_msgs/HumanStateMsg.h"

namespace amrl_msgs
{
template <class ContainerAllocator>
struct HumanStateArrayMsg_ {
  typedef HumanStateArrayMsg_<ContainerAllocator> Type;

  HumanStateArrayMsg_()
  : header()
  , human_states()
  {
  }

  HumanStateArrayMsg_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , human_states(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::vector< ::amrl_msgs::HumanStateMsg_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::amrl_msgs::HumanStateMsg_<ContainerAllocator> >::other >  _human_states_type;
  std::vector< ::amrl_msgs::HumanStateMsg_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::amrl_msgs::HumanStateMsg_<ContainerAllocator> >::other >  human_states;


  typedef boost::shared_ptr< ::amrl_msgs::HumanStateArrayMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::amrl_msgs::HumanStateArrayMsg_<ContainerAllocator>  const> ConstPtr;
}; // struct HumanStateArrayMsg
typedef  ::amrl_msgs::HumanStateArrayMsg_<std::allocator<void> > HumanStateArrayMsg;

typedef boost::shared_ptr< ::amrl_msgs::HumanStateArrayMsg> HumanStateArrayMsgPtr;
typedef boost::shared_ptr< ::amrl_msgs::HumanStateArrayMsg const> HumanStateArrayMsgConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::amrl_msgs::HumanStateArrayMsg_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::amrl_msgs::HumanStateArrayMsg_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace amrl_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::amrl_msgs::HumanStateArrayMsg_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::amrl_msgs::HumanStateArrayMsg_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::amrl_msgs::HumanStateArrayMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "49fe6d99468607352f144599e4a4afcb";
  }

  static const char* value(const  ::amrl_msgs::HumanStateArrayMsg_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x49fe6d9946860735ULL;
  static const uint64_t static_value2 = 0x2f144599e4a4afcbULL;
};

template<class ContainerAllocator>
struct DataType< ::amrl_msgs::HumanStateArrayMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "amrl_msgs/HumanStateArrayMsg";
  }

  static const char* value(const  ::amrl_msgs::HumanStateArrayMsg_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::amrl_msgs::HumanStateArrayMsg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "std_msgs/Header header\n\
HumanStateMsg[] human_states\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: amrl_msgs/HumanStateMsg\n\
geometry_msgs/Pose2D pose\n\
geometry_msgs/Vector3 translational_velocity\n\
float64 rotational_velocity\n\
int64 id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose2D\n\
# Deprecated\n\
# Please use the full 3D pose.\n\
\n\
# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n\
\n\
# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n\
\n\
\n\
# This expresses a position and orientation on a 2D manifold.\n\
\n\
float64 x\n\
float64 y\n\
float64 theta\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const  ::amrl_msgs::HumanStateArrayMsg_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::amrl_msgs::HumanStateArrayMsg_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::amrl_msgs::HumanStateArrayMsg_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::amrl_msgs::HumanStateArrayMsg_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.human_states);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct HumanStateArrayMsg_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::amrl_msgs::HumanStateArrayMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::amrl_msgs::HumanStateArrayMsg_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "human_states[]" << std::endl;
    for (size_t i = 0; i < v.human_states.size(); ++i)
    {
      s << indent << "  human_states[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::amrl_msgs::HumanStateMsg_<ContainerAllocator> >::stream(s, indent + "    ", v.human_states[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // AMRL_MSGS_MESSAGE_HUMANSTATEARRAYMSG_H

